version: '3'

services:
  web:
    build: .
    command: sh -c "uvicorn main:app --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'tu_contrasena'
      MYSQL_DATABASE: 'fastgallery'
    ports:
      - "3306:3306" 
    volumes:
      - /var/lib/mysql

